# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RRHH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Ingrese su nombre: ', max_length=50)),
                ('Telephone', models.IntegerField(help_text='Ingrese su numero de telefono: ', max_length=10)),
                ('Sex', models.CharField(help_text='Ingrese su sexo: ', max_length=1)),
                ('Fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
